update

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -16,9 +16,9 @@ jobs:
             echo "::error::DOCKER_ACTION_TOKEN secret is not set" >&2
             exit 1
           fi
-          if [ x"${DOCKER_ACTION_REPO}" = x"" ]
+          if [ x"${{ secrets.DOCKER_ACTION_REPO }}" = x"" ]
           then
-            echo "::error::DOCKER_ACTION_REPO env is not set" >&2
+            echo "::error::DOCKER_ACTION_REPO secret is not set" >&2
             exit 1
           fi
 
@@ -30,5 +30,5 @@ jobs:
             -X POST \
             -H "accept: application/vnd.github.v3+json" \
             -H "authorization"="Bearer ${Token}"; \
-            https://api.github.com/repos/${DOCKER_ACTION_REPO}/actions/workflows/update.yml/dispatches \
+            https://api.github.com/repos/${{ secrets.DOCKER_ACTION_REPO }}/actions/workflows/update.yml/dispatches \
             -d '{"event_type":"Update from Swow", "client_payload":{"ref":"'${ref##*/}'"}}'
